name: macos

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: macos-11  } # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#xcode
        - { os: macos-12 } # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md#xcode

    name: "${{matrix.config.os}}"
    steps:
    - uses: actions/checkout@v2

    - name: Build Release
      run: |
        rm -rf build
        cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DSTATIC_TODO_GIT_USERNAME=jatin
        cmake --build build --config Release

    - name: Build Debug
      run: |
        rm -rf build
        cmake -Bbuild -DCMAKE_BUILD_TYPE=Debug -DSTATIC_TODO_GIT_USERNAME=jatin
        cmake --build build --config Debug
