name: ubuntu

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
        - { cc: "gcc-11", cxx: "g++-11" }

    name: "${{matrix.compiler.cc}}"
    steps:
    - uses: actions/checkout@v2

    - name: Configure gcc
      run: |
        if [[ "${{matrix.compiler.cc}}" == "gcc"* ]]; then
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt update
          sudo apt install ${{matrix.compiler.cxx}} -y
        fi

    - name: Build Release
      run: |
        rm -rf build
        cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=${{matrix.compiler.cxx}} -DSTATIC_TODO_GIT_USERNAME=jatin
        cmake --build build --config Release

    - name: Build Debug
      run: |
        rm -rf build
        cmake -Bbuild -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=${{matrix.compiler.cxx}} -DSTATIC_TODO_GIT_USERNAME=jatin
        cmake --build build --config Debug
